### ISSUE TITLE
TODO: make it so that it removes the @ and instance but keeps the name

### ISSUE THREAD

**Issue by cattebune** [Lynnesbian/mstdn-ebooks#10]
TODO on https://github.com/Lynnesbian/mstdn-ebooks/blob/dd7a4efd95651516cfb3c3d3e5882ef94a8d42e0/main.py#L57

Not sure if this is still valid but still listed as a TODO. @Lynnesbian can you confirm if this is still broken as it seems to be working on live bots?

**Comment by Lynnesbian** [comment]
oh yeah i fixed that ages ago
thanks kaylee

**Comment by Lynnesbian** [comment]
i'll fix it when i'm on my computer uwu

**Comment by cattebune** [comment]
:purple_heart: Thought so, just thought best to double check haha
